# Create React App을 위한 Dockerfile
FROM node:14

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 파일 복사 및 종속성 설치
COPY package.json package-lock.json ./
RUN npm install

# 애플리케이션 코드 복사
COPY . .

# 빌드
RUN npm run build

# 정적 파일을 제공하기 위한 서버 설치
RUN npm install -g serve

# 앱을 3000번 포트에서 실행
CMD ["serve", "-s", "build", "-l", "3000"]
