version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - facemood_api
      - chatbot_api

  facemood_api:
    build:
      context: ./ai_api/facemood_api/
      dockerfile: ./dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai_api/facemood_api:/app

  chatbot_api:
    build:
      context: ./ai_api/chatbot_api/
      dockerfile: ./dockerfile
    env_file:
      - ./ai_api/chatbot_api/.env
    ports:
      - "5001:5001"
    volumes:
      - ./ai_api/chatbot_api:/app
