# -*- coding: utf-8 -*-
"""music_recommend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HC-idTorqv2CtdY1E4ILh4_j7D2Sglv7
"""

def read_labeled_songs_file(file_path):
    labeled_songs = {}
    with open(file_path, 'r') as file:
        for line in file:
            song, emotion = line.strip().split(',' , 1)
            if emotion.lower() in labeled_songs:
                labeled_songs[emotion.lower()].append(song)
            else:
                labeled_songs[emotion.lower()] = [song]
    return labeled_songs

def find_songs_by_emotion(emotion, labeled_songs):
    songs = labeled_songs.get(emotion.lower())
    if songs:
        return songs[:5]  # 최대 5개의 곡을 반환
    else:
        return "Sorry, I couldn't find songs for that emotion."

# 파일 경로
file_path = "/tmp/music.txt"

# 곡과 감정이 라벨링된 데이터셋 읽어오기
labeled_songs_dataset = read_labeled_songs_file(file_path)

# 사용자 입력 받기
emotion = input("Enter your emotion (happy, angry, sad, anxious): ")

# 입력된 감정에 대한 곡 제목 5개 출력
recommended_songs = find_songs_by_emotion(emotion, labeled_songs_dataset)
print("Recommended songs for", emotion, ":", recommended_songs)