# 기본 이미지 설정
FROM python:3.8-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요 패키지 설치
COPY requirements.txt ./
RUN pip install -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# .env 파일 복사
COPY .env .env

# 환경 변수 로드
RUN pip install python-dotenv

# 앱을 5001번 포트에서 실행
EXPOSE 5001
CMD ["python", "app.py"]
