# Flask 앱을 위한 Dockerfile
FROM python:3.8-slim

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 파일 복사 및 종속성 설치
COPY requirements.txt ./
RUN pip install -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# 앱을 5000번 포트에서 실행
EXPOSE 5000
CMD ["python", "main.py"]